pitaya:
  metrics:
    prometheus:
      enabled: true
    custom:
      counters:
      - subsystem: room
        name: my_counter
        help: a counter example
        labels: ['tag1', 'tag2']
      gauges:
      - subsystem: room
        name: my_gauge_1
        help: a gauge example
        labels: ['tag1']
      - subsystem: room
        name: my_gauge_2
        help: a gauge example
        labels: ['tag2']
      summaries:
      - subsystem: room
        name: my_summary
        help: a summary example
        objectives: {0.7: 0.05, 0.9: 0.01, 0.99: 0.001}
        labels: ['tag1']
